default_deploy_mode = "upload"

[upload]
# official server config
#auth_token = "YOUR TOKEN"

# Private server config
username = "YOUR_EMAIL"
password = "YOUR_PASSWORD"
hostname = "server1.screepspl.us"

# Common config
branch = "default"
ssl = true
port = 443

# hostname = "localhost"
# ssl = false
# port = 21025

# for full syntax, see
# https://github.com/daboross/screeps-in-rust-via-wasm/blob/master/screeps-defaults.toml
